<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Agence Eno Lyon</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.3/css/bootstrap.min.css" integrity="sha512-oc9+XSs1H243/FRN9Rw62Fn8EtxjEYWHXRvjS43YtueEewbS6ObfXcJNyohjHqVKFPoXXUxwc+q1K7Dee6vv9g==" crossorigin="anonymous" />

    <link rel="stylesheet" href="css/index.css">
</head>
<body>
<header>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Agence Lyon</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="../templates/index.phtml">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="../templates/add_product.phtml">Créer une annonce</a>
                        <span class="sr-only">(current)</span>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>
</header>

<!-- Page Content -->
<div class="container">

    <div class="row mt-5">

        <div class="col-md-12">
            <h1 class="my-4"><?=$pageTitle;?></h1>

            <main>
            <form action="admin_add_product.php" method="POST">
    <fieldset>
        <legend>Ajouter un produit</legend>
        <div class="form-group">
            <label for="titre">titre</label>
            <input required type="text" class="form-control" id="titre" name="titre">
        </div>
        <div class="form-group">
            <label for="titre">adresse</label>
            <input required type="text" class="form-control" id="adresse" name="adresse">
        </div>
        <div class="form-group">
            <label for="titre">ville</label>
            <input required type="text" class="form-control" id="ville" name="ville">
        </div>
        <div class="form-group">
            <label for="price">cp</label>
            <input required type="number" class="form-control" id="cp" name="cp">
        </div>
        <div class="form-group">
            <label for="description">description</label>
            <textarea required name="description" id="description"></textarea>
        </div>
        <div class="form-group">
            <label for="picture">photo</label>
            <input type="text" class="form-control" id="photo" name="photo">
        </div>
        <div class="form-group">
            <label for="price">prix</label>
            <input required type="number" min="0" step="0.01" class="form-control" id="Prix" name="Prix">
        </div>
        <div class="form-group">
            <label for="stock">surface</label>
            <input required type="number" min="0" class="form-control" id="surface" name="surface">
        </div>
        <div class="form-group">
            <label for="category">type</label>
            <select name="category" required>
                <?php foreach ($categories as $category): ?>
                    <option value="<?=$category['id'];?>"><?=$category['label'];?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </fieldset>
    <input type="submit" value="Enregistrer">                 
</form>


               
            </main>
        </div>

    </div>

    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
        </div>
    </footer>
</div>

<!-- Bootstrap core JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>

</body>
</html>